config/routes.rb
Rails.application.routes.draw do
  root 'landing_page#index'
  post 'copy/:id', to: "lists#copy", as: 'copy'


  mount Commontator::Engine => '/commontator'

  resources :lists do 
    resources :items
  end

  devise_for :users
end

app/models/commontator_comment.rb
class CommontatorComment < ActiveRecord::Base
	def display
	  creator = User.find(self.creator_id)
		"Comment By: #{creator.email} \n Body: #{self.body}"
	end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  acts_as_commontable
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, dependent: :destroy
  belongs_to :user
  acts_as_commontable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lists, dependent: :destroy

  acts_as_commontator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 	before_action :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
  	@conversations = current_user.mailbox.conversations
  end

  def show
  	@conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
  	@recipients = User.all - current_user
  end
  def create
  	recipient = User.find(params[:user_id])
  	receipt   = current_user.send_message(recipient, params[:body], params[:subject])
  	redirect_to conversation_path(receipt.conversation)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :list, only: [:edit, :new]
  before_action :item, only: [:show, :edit, :destroy, :update]
  def index
  	@items = current_user.lists.find(params[:list_id]).items
  end

  def show
  end

  def edit
  end

  def new
  	@item = Item.new
  end

  def create
    @item = current_user.lists.find(params[:list_id]).items.new(item_params)
    if @item.save
      redirect_to list_path(params[:list_id])
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to list_item_path(@item.list, @item)
    else
      render :edit
  	end
	end
# Method for create
	def destroy
    @item.destroy
    redirect_to list_path(params[:list_id])
  end

	private

		def item_params
	    params.require(:item).permit(:name, :description, :like, :complete, :classification)
	  end

		def item
	  	@item = Item.find(params[:id])
	  end

    def list
      @list = List.find(params[:list_id])
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  

  def index
    @ex_lists = List.all
    @lists = current_user.lists.paginate(page: params[:page], :per_page => 2)
    @comments = CommontatorComment.all.where(deleted_at: nil)
  end

  def show
  	# commontator_thread_show(@list) 
  end

  def edit
  end

  def new
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :list, only: [:show, :edit, :update, :destroy]
  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find(params[:id])
    commontator_thread_show(@list)
  end

  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def copy
    copy_list = List.find(params[:id])
    current_user.lists << copy_list.deep_clone(include: :items)
    current_user.save
    redirect_to root_path
  end

  def edit
  end

  def update
    if @list.update
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def copy
    copy_list = List.find(params[:id])
    current_user.lists << copy_list.deep_clone(include: :items)
    current_user.save
    redirect_to root_path
  end

  def destroy
    @list.destroy
    redirect_to root_path
  end

  private

    def list_params
      params.require(:list).permit(:name, :description)
    end

    def list
      @list = current_user.lists.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/conversations/index.html.erb
<h1>All Conversations</h1>

<% @conversations.each do |conversation| %>
	<div>
		<% link_to conversation.subject, conversation_path(conversation) %>
	</div>
<% end %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_tag conversations_path, method: :post do %>
	<div>
		<%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name)%>
	</div>
	<div>
		<%=text_field_tag :subject, nil, placeholder: "Subject"%>
	</div>
	<div>
		<%=text_area_tag :body, nil, placeholder: "Leave a Comment"%>
	</div>

	<%= submit_tag %>
<% end %>

app/views/conversations/show.html.erb
<h1><%=@conversation.subject%></h1>

<% @conversation.receipts_for(current_user).each do |receipt| %>
	<div>
		<div><%=receipt.message.sender.name %> commented: </div>
		<p><%=receipt.message.message.body %></p>
	</div>
<% end %>


<%= form_tag conversation_messages_path(@conversation), method: :post do %>
	<div>
			<%=text_area_tag :body %>
	</div>

	<%=submit_tag%>
<% end %>

app/views/items/_form.html.erb
<%= form_for [@list, @item] do |f|%>

	<div class="row">
		<div class="input-field col s4 offset-s4">
			<%= f.label :name, :class => "validate grey-text text-lighten-5"%>
			<%= f.text_field :name %>
		</div>
	</div>

	<div class="row">
		<div class="input-field col s4 offset-s4">
			<%= f.label :description, :class => "validate grey-text text-lighten-5" %>
			<%= f.text_area :description, :class => "materialize-textarea" %>
		</div>

		<div class="input-field col s4 offset-s4">
			<%= f.check_box :complete %>
			<%= f.label :complete %>
		</div>
	</div>

		<%= f.label :classification, :class => "validate grey-text text-lighten-5" %>
		<div class="row">
			<div class="input-field col s4 offset-s4">
			<%= f.select :classification, options_for_select(["Select One", "travel","sports","shows/plays","Miscellaneous"]), {}, class: "browser-default" %>
		</div>
	</div>


	<%= f.submit, :class => "waves-effect waves-light btn blue-text text-lighten-4" %>

<% end %>

app/views/items/edit.html.erb
<div class="center-align container">
	<h1 class="grey-text">Edit Item</h1>

	<%= render(partial: 'form')%>
</div>

app/views/items/index.html.erb
<h1>Items Index</h1>

app/views/items/new.html.erb
<div class="center-align container">
	<h1 class="grey-text">Create New Item</h1>

	<%= render(partial: 'form')%>
</div>

app/views/items/show.html.erb
<h1 class="grey-text">Your item</h1>

<%= @item.name %>
<%= @item.description %>

<%= link_to "Edit this Item", edit_list_item_path(@item.list, @item) %>
<%= link_to "Delete this item", list_item_path(@item.list_id, @item), method: :delete %>

app/views/landing_page/_cardsrow.html.erb
<div class="col s12 m9">
  <% if @lists.any? %>
      <% @lists.each do |list| %>
        <div class="row">
          <div class="col s12 m12">
            <div class="card indigo">
              <div class="card-content white-text">
                <span class="card-title activator"><%= link_to list.name, list_path(list)%><i class="material-icons right">more_vert</i></span>
                <p><%= list.description %></p>
              </div>
              <div class="card-action">
                <%= link_to 'Add new item', new_list_item_path(list, @item), class: "blue-text text-lighten-4"%>
                <%= link_to "Delete this list",  list_path(list), method: :delete, class: "blue-text text-lighten-4" %>
              </div>
              <div class="card-reveal">
                <% if list.items.count >= 2 %>
                  <span class="card-title grey-text text-darken-4">Some items on the list include:<i class="material-icons right">close</i></span>
                  <p><%= list.items.sample[:name] %> and <%= list.items.sample[:name] %></p>
                <% elsif list.items.count == 1
                   %>
                   <span class="card-title grey-text text-darken-4">Some items on the list include:<i class="material-icons right">close</i></span>
                   <p><%= list.items.sample[:name] %></p>
                <% elsif %>
                  <span class="card-title grey-text text-darken-4"><%= list.name %><i class="material-icons right">close</i></span>
                  <p>You don't have anything included on this list. Try adding something that you would like to do!</p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  <% else %>
        <h5>You haven't made a list yet. Go create one!</h5>
        <!-- show suggestion -->
  <% end %>
</div>

app/views/landing_page/_feed.html.erb
<div class="col s12 m3">
  <h5 class="white-text">Feed</h5>
  <ul>
    <% @comments.each do |comment| %>
      <li>
        <%= comment.display %>
        <hr />
      </li>
    <% end %>
  </ul>
</div>

app/views/landing_page/_suggestions.html.erb
<a class="waves-effect waves-light btn modal-trigger blue-text text-lighten-4" href="#modal1">Suggestion</a>

 <div id="modal1" class="modal bottom-sheet">
   <div class="modal-content">
    <h4>Suggestions</h4>
     <ul class="collection">
      <% @ex_lists.each do |list| %>
         <li class="collection-item avatar">
          <i class="material-icons circle green">assessment</i>
          <span class="Title"><%= list.name %></span>
          <p><%= list.description %></p>
          <form method='post' action="/copy/<%= list.id %>">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <button type='submit' class= "btn">+</button>
          </form>
          <!-- <button class="btn" href="/copy" type="post">
            <i class="material-icons top">control_point</i>
          </button> -->
         </li>
       <% end %>
     </ul>
   </div>
   <div class="modal-footer">
     <%= link_to 'Make A New List', new_list_path, class: "modal-action close waves-effect waves-green btn right" %>
   </div>
 </div>

app/views/landing_page/edit.html.erb
<h1>LandingPage#edit</h1>
<p>Find me in app/views/landing_page/edit.html.erb</p>

app/views/landing_page/index.html.erb
<div class="container">
	<div>

		<h3 class="grey-text">Welcome, <%= current_user.email%>!</h3>
	</div>
	
	<div>
			<%= link_to 'New Bucket List', new_list_path %>
			<br />
		  <%= render(partial: 'suggestions') %>
	</div>

	<div id="modal1" class="modal bottom-sheet">
	  <div class="modal-content">
	   <h4>Suggestions</h4>
	    <ul class="collection">
	    	<% @ex_lists.each do |list| %>
	        <li class="collection-item avatar">
	        	<i class="material-icons circle green">assessment</i>
	        	<span class="Title"><%= list.name %></span>
	        	<p><%= list.description %></p>
	        	<form method='post' action="/copy/<%= list.id %>">
	        		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	        	  <button type='submit' class= "btn"><i class="material-icons top">control_point</i></button>
	        	</form>
	        </li>
	      <% end %>
	    </ul>
	  </div>
	  <div class="modal-footer">
	    <%= link_to 'Make A New List', new_list_path, class: "modal-action close waves-effect waves-green btn right" %>
	  </div>
	</div>
	<div class="row">
		<%= render(partial: 'cardsrow')  %>
		<%= render(partial: 'feed') %>
	</div>	
	<%= will_paginate @lists %>

</div>

app/views/landing_page/new.html.erb
<h1>LandingPage#new</h1>
<p>Find me in app/views/landing_page/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l12 s12">
        <h5 class="white-text">Bucket List</h5>
        <p class="grey-text text-lighten-4">With This Tool, You Can Accomplish Everything On Your Bucketlist.</p>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Copyright BL
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'Edit Profile', edit_user_registration_path %> </li>
  <li class="divider"></li>
  <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <%= image_tag("logo-white.png", :alt => "bucket", class: "img") %>
    <%= link_to 'BUCKET LIST', root_path, class: "brand-logo" %>
    <ul class="right hide-on-med-and-down">
       <li class=" avatar"><i class="medium material-icons circle">perm_identity</i></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Profile<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketList</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <header>
    <% if flash.any? %>
    	<% flash.each do |key, value| %>
    	 <script>
    	   Materialize.toast("<%= value %>", 4000, 'rounded indigo lighten-2');
    	 </script>
    	<% end %>
    <% end %>

    <%= render(partial: 'layouts/navbar') %>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>
    <%= render(partial: 'layouts/footer') %>
  </footer>
</body>
</html>

app/views/lists/_form.html.erb
	<%= form_for @list do |f|%>
	<div class="row">
		<div class="input-field col s4 offset-s4">
		<%= f.label :name, :class => "validate grey-text text-lighten-5"%>
		<%= f.text_field :name %>
		</div>
	</div>

	<div class="row">
		<div class="input-field col s4 offset-s4">
		<%= f.label :description, :class => "validate grey-text text-lighten-5" %>
		<%= f.text_area :description, :class => "materialize-textarea" %>
		</div>
	</div>

		<%= f.submit :class => "waves-effect waves-light btn blue-text text-lighten-4"%>

	<% end %>

app/views/lists/edit.html.erb
<div class="center-align container">
	<h1 class="grey-text">Editing list</h1>

	<%= render(partial: 'form')%>
</div>

app/views/lists/new.html.erb
<div class="center-align container">
	<h1 class="grey-text">New List</h1>

	<%= render(partial: 'form')%>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1 class="grey-text">Bucket List</h1>

  <% if @list.items.any? %>
    <div class="row">
      <% @list.items.each do |i| %>
        <div class="col s12 m6">
          <div class="card indigo z-depth-3">
            <div class="card-content white-text">
              <span class="card-title"><%= link_to i.name, list_item_path(@list, i) %></span>
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">Like</a>
              <a href="#">Comment</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    </ul>
  <% else %>
    <p>Add an item!</p>
  <% end %>

  
  <%= link_to 'Add new item', new_list_item_path(@list), :class => "waves-effect waves-light btn modal-trigger blue-text text-lighten-4"%>
  <%= link_to "Delete this list",  list_path(@list), method: :delete, :class => "waves-effect waves-light btn modal-trigger blue-text text-lighten-4" %>
  <%= commontator_thread(@list) %>
</div>